Sprint 1 merged
umgc/summer2021.bravo pull request #12
Opened 2021-07-02 00:32 UTC by MDunning14

Merge the changes up to the Milestone 2 demo into Main

2021-07-02 00:38 UTC, abaileys approved these changes

2021-07-04 17:31 UTC, willywil548 requested changes
Please update the namespace before merge

2021-07-04 17:31 UTC, willywil548 commented on harkify/android/app/src/main/AndroidManifest.xml
>      package="com.example.helloworld">
Probably should update the namespace

2021-07-04 17:31 UTC, willywil548 commented on harkify/lib/notedetails.dart
> +                                    // dateString[0] + ":" + dateString[1],
Looks like this isn't needed anymore

2021-07-04 17:31 UTC, willywil548 commented on harkify/lib/recordnote.dart
> +  //final VoiceHelper _helper = VoiceHelper();
Some leftover testing code?

2021-07-04 17:31 UTC, willywil548 commented on harkify/lib/textnoteservice.dart
> +    //docsDirectory = await fileSystem.systemTempDirectory.createTemp('harkify');
More leftover testing code?

2021-07-15 15:43 UTC, abaileys approved these changes

2021-07-16 00:52 UTC, abaileys approved these changes

2021-07-16 00:58 UTC, willywil548 reviewed
LGTM, Please resolve the Lint erros

2021-07-16 00:58 UTC, willywil548 commented on harkify/android/app/build.gradle
>          applicationId "com.example.helloworld"
application id isn't really hello world is it?

2021-07-16 01:11 UTC, closed without merging

2021-07-16 01:11 UTC, MDunning14 commented
Too many changes to track here, we're closing this and starting over